development:
  adapter: postgresql
  database: typo_dev
  host: localhost
  username: typo

test:
  adapter: postgresql
  database: typo_tests
  host: localhost
  username: typo

production:
  adapter: postgresql
  database: typo_dev
  host: localhost
  username: typo
